carro/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.carro_detalle, name="carro_detalle"),
    path('agregar/', views.carro_agregar, name="carro_agregar"),
    path('eliminar/', views.carro_eliminar, name="carro_eliminar"),
    path('eliminar_general/', views.carro_eliminar_general, name="carro_eliminar_general"),
    path('actualizar/', views.carro_actualizar, name="carro_actualizar"),
    path('pdf/', views.generar_pdf, name='generar_pdf'),
]

mecanico_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views
from .views import *
from carro.views import generar_pdf

# Configuracion urls para API
router = routers.DefaultRouter()
router.register('empleados', EmpleadoViewSet)
router.register('servicios', ServicioViewSet)
router.register('productos', ProductoViewSet)

urlpatterns = [
    # Index
    path('', views.index, name = 'index'),
    path('nosotros/', views.nosotros, name = 'nosotros'),
    # Productos
    path('productos/', views.productos, name="productos"),
    path('productos/<int:pk>', views.producto_id, name = 'producto_id'),
    path('productos/add/', views.productosadd, name="productosadd"),
    path('productos/crud/update/<id>/', views.productosupdate, name="productosupdate"),
    path('productos/crud/delete/<id>/', views.productosdelete, name="productosdelete"),
    # Compras
    # path('registrar-compra/', RegistrarCompraView.as_view(), name='registrar_compra'),
    path('historial-compras/', historial_compras, name='historial_compras'),
    # Servicios
    path('servicios/', views.servicios, name="servicios"),
    path('servicios/add/', views.serviciosadd, name="serviciosadd"),
    path('servicios/crud/update/<id>/', views.serviciosupdate, name="serviciosupdate"),
    path('servicios/crud/delete/<id>/', views.serviciosdelete, name="serviciosdelete"),
    # Categorias
    path('categoria/<str:foo>', views.categoria, name = 'categoria'),
    # Login
    path('login/', views.login_user, name = 'login'),
    path('logout/', views.logout_user, name = 'logout'),
    # AXES
    path('account_locked/', views.account_locked, name='account_locked'),
    # Registro
    path('register/', views.register_user, name = 'register'),
    # Usuario
    path('actualizar_usuario/', views.actualizar_usuario, name = 'actualizar_usuario'),
    path('actualizar_info/', views.actualizar_info, name = 'actualizar_info'),
    # Empleados
    path('empleados/', views.empleados, name="empleados"),
    path('empleados/add/', views.empleadosadd, name="empleadosadd"),
    path('empleados/crud/update/<int:id>/', views.empleadosupdate, name="empleadosupdate"),
    path('empleados/crud/delete/<int:id>/', views.empleadosdelete, name="empleadosdelete"),
    # API
    path('api/', include(router.urls)),
    path('empleadosapi/', empleadosapi, name="empleadosapi"),
    path('serviciosapi/', serviciosapi, name="serviciosapi"),
    path('productosapi/', productosapi, name="productosapi"),
    # PDF
    path('pdf/', generar_pdf, name='generar_pdf'),
]

tienda/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
import datetime
import requests
import json

# API
class Mindicador:
 
    def __init__(self, indicador, year):
        self.indicador = indicador
        self.year = year
    
    def InfoApi(self):
        # En este caso hacemos la solicitud para el caso de consulta de un indicador en un año determinado
        url = f'https://mindicador.cl/api/{self.indicador}/{self.year}'
        response = requests.get(url)
        data = json.loads(response.text.encode("utf-8"))
        # Para que el json se vea ordenado, retornar pretty_json
        pretty_json = json.dumps(data, indent=2)
        return data

# Empleado
class Empleado(models.Model):
    nombre = models.CharField(max_length=100)
    tipo = models.CharField(max_length=150)
    imagen = models.ImageField(upload_to='uploads/empleado/', null=True, blank=True)

    def __str__(self):
        return self.nombre

# Cliente
class Cliente(models.Model):
    p_nombre = models.CharField(max_length=50)
    s_nombre = models.CharField(max_length=50)
    telefono = models.CharField(max_length=10)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.p_nombre} {self.s_nombre}'
    
    class Meta:
        verbose_name_plural = 'Clientes'

# Perfiles
class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    date_modified = models.DateTimeField(User, auto_now=True)
    telefono = models.CharField(max_length=20, blank=True)
    direccion = models.CharField(max_length=200, blank=True)
    direccion_dos = models.CharField(max_length=200, blank=True)
    ciudad = models.CharField(max_length=200, blank=True)
    comuna = models.CharField(max_length=200, blank=True)
    zipcode = models.CharField(max_length=200, blank=True)
    pais = models.CharField(max_length=200, blank=True)
    carrito_viejo = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.usuario.username
    
def crear_perfil(sender, instance, created, **kwargs):
    if created:
        user_profile = Perfil(usuario=instance)
        user_profile.save()

post_save.connect(crear_perfil, sender=User)


# Categoria de productos
class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name_plural = 'Categorias'

# Producto
class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(default=0, decimal_places=2, max_digits=6)
    precio_base = models.DecimalField(max_digits=10, decimal_places=2, default=10)
    multiplicador = models.PositiveIntegerField(default=1)
    precio_final = models.DecimalField(max_digits=10, decimal_places=2, default=0)    
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, default=1)
    descripcion = models.CharField(max_length=250, default='', blank=True, null= True)
    imagen = models.ImageField(upload_to='uploads/product/')

    # En Oferta
    is_oferta = models.BooleanField(default=False)
    oferta_precio = models.DecimalField(default=0, decimal_places=2, max_digits=6)

    def save(self, *args, **kwargs):
        # Calcular el precio final antes de guardar
        self.precio_final = round(self.precio_base * self.multiplicador)

        super(Producto, self).save(*args, **kwargs)

    def __str__(self):
        return self.nombre    
    
    class Meta:
        verbose_name_plural = 'Productos'

class Compra(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto, through='CompraProducto')
    total_pagado = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_compra = models.DateTimeField(auto_now_add=True)

class CompraProducto(models.Model):
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)

# Servicio
class Servicio(models.Model):
    nombre_servicio = models.CharField(max_length=200)
    descripcion_servicio = models.TextField(max_length=550)
    imagen_servicio = models.ImageField(upload_to='uploads/servicio/', null=True, blank=True)
    def __str__(self):
        return self.nombre_servicio

# Orden
class Orden(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=1)
    direccion = models.CharField(max_length=100, default='', blank=True)
    telefono = models.CharField(max_length=50, default='', blank=True)
    fecha = models.DateField(default=datetime.datetime.today)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.producto
    
    class Meta:
        verbose_name_plural = 'Ordenes'

tienda/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django_recaptcha.fields import ReCaptchaField
from captcha.fields import CaptchaField
from .models import *

# Usuario
class UserInfoForm(forms.ModelForm):
    telefono = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Telefono'}), required=False)
    direccion = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Dirección 1'}), required=False)
    direccion_dos = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Dirección 2'}), required=False)
    ciudad = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Ciudad'}), required=False)
    comuna = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Comuna'}), required=False)
    zipcode = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Zipcode'}), required=False)
    pais = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Pais'}), required=False)

    class Meta:
        model = Perfil
        fields = ('telefono', 'direccion', 'direccion_dos', 'ciudad', 'comuna', 'zipcode', 'pais',)

# Empleado
class EmpleadoForm(ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Empleado
        fields = '__all__'

# Servicio
class ServicioForm(ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Servicio
        fields = '__all__'

# Producto
class ProductoForm(ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Producto
        fields = '__all__'

# Sesión
class UpdateUserForm(UserChangeForm):
    captcha = CaptchaField()

    password = None
    email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Correo electronico'}))
    first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Nombre'}))
    last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Apellido'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UpdateUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Usuario'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Obligatorio. 150 caracteres o menos. Solo letras, digitos y @/./+/-/_</small></span>'

class SignUpForm(UserCreationForm):
    captcha = CaptchaField()

    email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Correo electronico'}))
    first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Nombre'}))
    last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Apellido'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Usuario'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Obligatorio. 150 caracteres o menos. Solo letras, digitos y @/./+/-/_</small></span>'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Contraseña'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Tú contraseña no puede ser muy similar a tu información personal.</li><li>Tu contraseña debe contener al menos 8 caracteres.</li><li>Tu contraseña no puede ser una contraseña común.</li><li>Tu contraseña no puede ser completamente númerica.</li></ul>'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirmar contraseña'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Para verificar, ingresa nuevamente la contraseña.</small></span>'

tienda/templates/tienda/productos/crud/add.html
{% extends 'base.html' %}
{% block content %}

<div class="d-flex justify-content-center p-3 text-primary-emphasis bg-dark-subtle border border-dark-subtle">
    <div class="card" style="width: 64rem;">
        <div class="card-header d-flex justify-content-center mt-1">
            <h5>Añadir producto</h5>
        </div>
        <div class="card-body">
            <form action="" method="POST" style="margin: 0 auto;" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="id_nombre" class="col-sm-4 col-form-label">Nombre:</label>
                    <div class="col-sm-4">
                        {{ form.nombre }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_descripcion" class="col-sm-4 col-form-label">Descripción:</label>
                    <div class="col-sm-4">
                        {{ form.descripcion }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_categoria" class="col-sm-4 col-form-label">Categoría:</label>
                    <div class="col-sm-4">
                        {{ form.categoria }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_precio_base" class="col-sm-4 col-form-label">Precio base:</label>
                    <div class="col-sm-4">
                        {{ form.precio }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_precio_base" class="col-sm-4 col-form-label">Precio base:</label>
                    <div class="col-sm-4">
                        {{ form.precio_base }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_multiplicador" class="col-sm-4 col-form-label">Multiplicador:</label>
                    <div class="col-sm-4">
                        <input type="number" id="id_multiplicador" name="multiplicador" value="{{ form.multiplicador.value|default:1 }}" min="1" step="1" onchange="actualizarPrecio()">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_precio_final" class="col-sm-4 col-form-label">Precio final:</label>
                    <div class="col-sm-4">
                        <input type="text" id="id_precio_final" name="precio_final" value="{{ form.precio_final.value }}" readonly>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_is_oferta" class="col-sm-4 col-form-label">En oferta:</label>
                    <div class="col-sm-4">
                        {{ form.is_oferta }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_oferta_precio" class="col-sm-4 col-form-label">Precio oferta:</label>
                    <div class="col-sm-4">
                        {{ form.oferta_precio }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_imagen" class="col-sm-4 col-form-label">Imagen:</label>
                    <div class="col-sm-4">
                        {{ form.imagen }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_captcha" class="col-sm-4 col-form-label">Captcha:</label>
                    <div class="col-sm-4">
                        {{ form.captcha }}
                    </div>
                </div>
                <div class="d-flex justify-content-center">
                    <input type="submit" value="Añadir" class="btn btn-success mx-1">
                    <input type="reset" value="Limpiar" class="btn btn-secondary mx-1">
                </div>
            </form>
            <h5 class="mt-3">{{ msj }}</h5>
        </div>
    </div>
</div>

<script>
    function actualizarPrecio() {
        let precioBase = parseFloat(document.getElementById("id_precio_base").value);
        let multiplicador = parseFloat(document.getElementById("id_multiplicador").value);
        let precioFinal = precioBase * multiplicador;
        precioFinal = Math.round(precioFinal)
        document.getElementById("id_precio_final").value = precioFinal.toFixed(2);
    }
</script>

{% endblock %}

tienda/templates/tienda/productos/crud/update.html
{% extends 'base.html' %}
{% block content %}

<div class="d-flex justify-content-center p-3 text-primary-emphasis bg-dark-subtle border border-dark-subtle">
    <div class="card" style="width: 64rem;">
        <div class="card-header d-flex justify-content-center mt-1">
            <h5>Modificar producto</h5>
        </div>
        <div class="card-body">
            <form action="" method="POST" style="margin: 0 auto;" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="id_nombre" class="col-sm-4 col-form-label">Nombre:</label>
                    <div class="col-sm-4">
                        {{ form.nombre }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_nombre" class="col-sm-4 col-form-label">Descripción:</label>
                    <div class="col-sm-4">
                        {{ form.descripcion }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_nombre" class="col-sm-4 col-form-label">Categoria:</label>
                    <div class="col-sm-4">
                        {{ form.categoria }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_nombre" class="col-sm-4 col-form-label">Precio:</label>
                    <div class="col-sm-4">
                        {{ form.precio }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_nombre" class="col-sm-4 col-form-label">En oferta?:</label>
                    <div class="col-sm-4">
                        {{ form.is_oferta }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_nombre" class="col-sm-4 col-form-label">Precio oferta:</label>
                    <div class="col-sm-4">
                        {{ form.oferta_precio }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_nombre" class="col-sm-4 col-form-label">Imagen:</label>
                    <div class="col-sm-4">
                        {{ form.imagen }}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_nombre" class="col-sm-4 col-form-label">Captcha:</label>
                    <div class="col-sm-4">
                        {{ form.captcha }}
                    </div>
                </div>
                <div class="d-flex justify-content-center">
                    <input type="submit" value="Modificar" class="btn btn-success mx-1">
                    <input type="reset" value="Limpiar" class="btn btn-secondary mx-1">
                </div>
            </form>
            <h5 class="mt-3">{{ msj }}</h5>
        </div>
    </div>
</div>

{% endblock %}