carro/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.carro_detalle, name="carro_detalle"),
    path('agregar/', views.carro_agregar, name="carro_agregar"),
    path('eliminar/', views.carro_eliminar, name="carro_eliminar"),
    path('eliminar_general/', views.carro_eliminar_general, name="carro_eliminar_general"),
    path('actualizar/', views.carro_actualizar, name="carro_actualizar"),
    path('pdf/', views.generar_pdf, name='generar_pdf'),
]

mecanico_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views
from .views import *
from carro.views import generar_pdf

# Configuracion urls para API
router = routers.DefaultRouter()
router.register('empleados', EmpleadoViewSet)
router.register('servicios', ServicioViewSet)
router.register('productos', ProductoViewSet)

urlpatterns = [
    # Index
    path('', views.index, name = 'index'),
    path('nosotros/', views.nosotros, name = 'nosotros'),
    # Productos
    path('productos/', views.productos, name="productos"),
    path('productos/<int:pk>', views.producto_id, name = 'producto_id'),
    path('productos/add/', views.productosadd, name="productosadd"),
    path('productos/crud/update/<id>/', views.productosupdate, name="productosupdate"),
    path('productos/crud/delete/<id>/', views.productosdelete, name="productosdelete"),
    # Compras
    # path('registrar-compra/', RegistrarCompraView.as_view(), name='registrar_compra'),
    path('historial-compras/', historial_compras, name='historial_compras'),
    # Servicios
    path('servicios/', views.servicios, name="servicios"),
    path('servicios/add/', views.serviciosadd, name="serviciosadd"),
    path('servicios/crud/update/<id>/', views.serviciosupdate, name="serviciosupdate"),
    path('servicios/crud/delete/<id>/', views.serviciosdelete, name="serviciosdelete"),
    # Categorias
    path('categoria/<str:foo>', views.categoria, name = 'categoria'),
    # Login
    path('login/', views.login_user, name = 'login'),
    path('logout/', views.logout_user, name = 'logout'),
    # AXES
    path('account_locked/', views.account_locked, name='account_locked'),
    # Registro
    path('register/', views.register_user, name = 'register'),
    # Usuario
    path('actualizar_usuario/', views.actualizar_usuario, name = 'actualizar_usuario'),
    path('actualizar_info/', views.actualizar_info, name = 'actualizar_info'),
    # Empleados
    path('empleados/', views.empleados, name="empleados"),
    path('empleados/add/', views.empleadosadd, name="empleadosadd"),
    path('empleados/crud/update/<int:id>/', views.empleadosupdate, name="empleadosupdate"),
    path('empleados/crud/delete/<int:id>/', views.empleadosdelete, name="empleadosdelete"),
    # API
    path('api/', include(router.urls)),
    path('empleadosapi/', empleadosapi, name="empleadosapi"),
    path('serviciosapi/', serviciosapi, name="serviciosapi"),
    path('productosapi/', productosapi, name="productosapi"),
    # PDF
    path('pdf/', generar_pdf, name='generar_pdf'),
]

tienda/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
import datetime
import requests
import json

# API
class Mindicador:
 
    def __init__(self, indicador, year):
        self.indicador = indicador
        self.year = year
    
    def InfoApi(self):
        # En este caso hacemos la solicitud para el caso de consulta de un indicador en un año determinado
        url = f'https://mindicador.cl/api/{self.indicador}/{self.year}'
        response = requests.get(url)
        data = json.loads(response.text.encode("utf-8"))
        # Para que el json se vea ordenado, retornar pretty_json
        pretty_json = json.dumps(data, indent=2)
        return data

# Empleado
class Empleado(models.Model):
    nombre = models.CharField(max_length=100)
    tipo = models.CharField(max_length=150)
    imagen = models.ImageField(upload_to='uploads/empleado/', null=True, blank=True)

    def __str__(self):
        return self.nombre

# Cliente
class Cliente(models.Model):
    p_nombre = models.CharField(max_length=50)
    s_nombre = models.CharField(max_length=50)
    telefono = models.CharField(max_length=10)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.p_nombre} {self.s_nombre}'
    
    class Meta:
        verbose_name_plural = 'Clientes'

# Perfiles
class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    date_modified = models.DateTimeField(User, auto_now=True)
    telefono = models.CharField(max_length=20, blank=True)
    direccion = models.CharField(max_length=200, blank=True)
    direccion_dos = models.CharField(max_length=200, blank=True)
    ciudad = models.CharField(max_length=200, blank=True)
    comuna = models.CharField(max_length=200, blank=True)
    zipcode = models.CharField(max_length=200, blank=True)
    pais = models.CharField(max_length=200, blank=True)
    carrito_viejo = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.usuario.username
    
def crear_perfil(sender, instance, created, **kwargs):
    if created:
        user_profile = Perfil(usuario=instance)
        user_profile.save()

post_save.connect(crear_perfil, sender=User)


# Categoria de productos
class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name_plural = 'Categorias'

# Producto
class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(default=0, decimal_places=2, max_digits=6)
    precio_base = models.DecimalField(max_digits=10, decimal_places=2, default=10)
    multiplicador = models.PositiveIntegerField(default=1)
    precio_final = models.DecimalField(max_digits=10, decimal_places=2, default=0)    
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, default=1)
    descripcion = models.CharField(max_length=250, default='', blank=True, null= True)
    imagen = models.ImageField(upload_to='uploads/product/')

    # En Oferta
    is_oferta = models.BooleanField(default=False)
    oferta_precio = models.DecimalField(default=0, decimal_places=2, max_digits=6)

    def save(self, *args, **kwargs):
        # Calcular el precio final antes de guardar
        self.precio_final = round(self.precio_base * self.multiplicador)

        super(Producto, self).save(*args, **kwargs)

    def __str__(self):
        return self.nombre    
    
    class Meta:
        verbose_name_plural = 'Productos'

class Compra(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto, through='CompraProducto')
    total_pagado = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_compra = models.DateTimeField(auto_now_add=True)

class CompraProducto(models.Model):
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)

# Servicio
class Servicio(models.Model):
    nombre_servicio = models.CharField(max_length=200)
    descripcion_servicio = models.TextField(max_length=550)
    imagen_servicio = models.ImageField(upload_to='uploads/servicio/', null=True, blank=True)
    def __str__(self):
        return self.nombre_servicio

# Orden
class Orden(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=1)
    direccion = models.CharField(max_length=100, default='', blank=True)
    telefono = models.CharField(max_length=50, default='', blank=True)
    fecha = models.DateField(default=datetime.datetime.today)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.producto
    
    class Meta:
        verbose_name_plural = 'Ordenes'

tienda/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django_recaptcha.fields import ReCaptchaField
from captcha.fields import CaptchaField
from .models import *

# Usuario
class UserInfoForm(forms.ModelForm):
    telefono = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Telefono'}), required=False)
    direccion = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Dirección 1'}), required=False)
    direccion_dos = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Dirección 2'}), required=False)
    ciudad = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Ciudad'}), required=False)
    comuna = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Comuna'}), required=False)
    zipcode = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Zipcode'}), required=False)
    pais = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Pais'}), required=False)

    class Meta:
        model = Perfil
        fields = ('telefono', 'direccion', 'direccion_dos', 'ciudad', 'comuna', 'zipcode', 'pais',)

# Empleado
class EmpleadoForm(ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Empleado
        fields = '__all__'

# Servicio
class ServicioForm(ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Servicio
        fields = '__all__'

# Producto
class ProductoForm(ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Producto
        fields = '__all__'

# Sesión
class UpdateUserForm(UserChangeForm):
    captcha = CaptchaField()

    password = None
    email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Correo electronico'}))
    first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Nombre'}))
    last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Apellido'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UpdateUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Usuario'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Obligatorio. 150 caracteres o menos. Solo letras, digitos y @/./+/-/_</small></span>'

class SignUpForm(UserCreationForm):
    captcha = CaptchaField()

    email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Correo electronico'}))
    first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Nombre'}))
    last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Apellido'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Usuario'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Obligatorio. 150 caracteres o menos. Solo letras, digitos y @/./+/-/_</small></span>'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Contraseña'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Tú contraseña no puede ser muy similar a tu información personal.</li><li>Tu contraseña debe contener al menos 8 caracteres.</li><li>Tu contraseña no puede ser una contraseña común.</li><li>Tu contraseña no puede ser completamente númerica.</li></ul>'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirmar contraseña'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Para verificar, ingresa nuevamente la contraseña.</small></span>'

tienda/templates/account_locked.html
{% extends 'base.html' %}
{% block content %}
    <!-- Header -->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Cuenta bloqueada!</h1>
                <p class="lead fw-normal text-white-50 mb-0">por muchos intentos fallidos. Intenta más tarde!</p>
            </div>
        </div>
    </header>
    
{% endblock %}

tienda/templates/actualizar_info.html
{% extends 'base.html' %}
{% block content %}

<!-- Header -->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Actualizar información de perfil.</h1>
            <p class="lead fw-normal text-white-50 mb-0">manten tus datos al día!</p>
        </div>
    </div>
</header>

<!-- Acerca de -->
<div class="container">
    <div class="row">
        <center>
            <div class="col-8">
                <br>
                <br>
                <br>
                <br>

                <form method="POST" action="{% url 'actualizar_info' %}">
                    {% csrf_token %}
                    <!-- Input -->
                    {{ form.as_p }}
                    <br>
                    <button type="submit" class="btn btn-secondary"> Actualizar </button>
                  </form>

                <br>
                <br>
                <br>
                <br>
            </div>
        </center>
    </div>
</div>

{% endblock %}

tienda/templates/actualizar_usuario.html
{% extends 'base.html' %}
{% block content %}

<!-- Header -->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Actualizar perfil</h1>
            <p class="lead fw-normal text-white-50 mb-0">manten tus datos al día!</p>
        </div>
    </div>
</header>

<!-- Acerca de -->
<div class="container">
    <div class="row">
        <center>
            <div class="col-8">
                <br>
                <br>
                <br>
                <br>

                <form method="POST" action="{% url 'actualizar_usuario' %}">
                    {% csrf_token %}
                    <!-- Input -->
                    {{ form_usuario.as_p }}
                    <br>
                    <button type="submit" class="btn btn-secondary"> Actualizar </button>
                  </form>

                <br>
                <br>
                <br>
                <br>
            </div>
        </center>
    </div>
</div>

{% endblock %}

tienda/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Mechá</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/icon.png' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    </head>
    <body>
        
        {% include 'navbar.html' %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
        
        {% block content %}
        {% endblock %}

        <!-- Footer-->
        <footer class="py-5 bg-dark" id="footer_base">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Mechá 2024</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

tienda/templates/categoria.html
{% extends 'base.html' %}
{% block content %}
    <!-- Header -->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">{{ categoria }}</h1>
                <p class="lead fw-normal text-white-50 mb-0">Compra con nosotros!</p>
            </div>
        </div>
    </header>
    <!-- Productos -->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
    
                {% for producto in productos %}
                    {% if producto.is_oferta %}
                        <div class="col mb-5">
                            <div class="card h-100">
                                <!-- Sale badge -->
                                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem;">Oferta</div>
                                <!-- Product image-->
                                <img class="card-img-top" src="{{ producto.imagen.url }}" alt="..." />
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{ producto.nombre }}</h5>
                                        <!-- Product price-->
                                        <strike>
                                            ${{ producto.precio }}
                                        </strike>
                                        &nbsp;
                                        ${{ producto.oferta_precio }}
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center">
                                        <a class="btn btn-outline-dark mt-auto" href="{% url 'producto' producto.id %}">Ver producto</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div class="col mb-5">
                            <div class="card h-100">
                                <!-- Product image-->
                                <img class="card-img-top" src="{{ producto.imagen.url }}" alt="..." />
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{ producto.nombre }}</h5>
                                        <!-- Product price-->
                                        ${{ producto.precio }}
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'producto' producto.id %}">Ver producto</a></div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}

            </div>
        </div>
    </section>
{% endblock %}

tienda/templates/historial_compras.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5">
        <h1>Historial de Compras</h1>
        <div class="list-group">
            {% if compras %}
                {% for compra in compras %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title">Compra realizada el {{ compra.fecha_compra }}</h5>
                            <p class="card-text">Total pagado: ${{ compra.total_pagado }}</p>
                            <ul class="list-group list-group-flush">
                                {% for cp in compra.compraproducto_set.all %}
                                    <li class="list-group-item">
                                        {{ cp.producto.nombre }} - Cantidad: {{ cp.cantidad }} - Precio: ${{ cp.precio }}
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="alert alert-info" role="alert">
                    No tienes compras realizadas.
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

tienda/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <!-- Header -->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Mechá</h1>
                <p class="lead fw-normal text-white-50 mb-0">con más de 10 años de experiencia, se grande, se Mechá!</p>
            </div>
        </div>
    </header>
    <!-- Productos -->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
    
                {% for producto in productos %}
                    {% if producto.is_oferta %}
                        <div class="col mb-5">
                            <div class="card h-100">
                                <!-- Sale badge -->
                                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem;">Oferta</div>
                                <!-- Product image-->
                                <img class="card-img-top" src="{{ producto.imagen.url }}" alt="..." />
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{ producto.nombre }}</h5>
                                        <!-- Product price-->
                                        <strike>
                                            ${{ producto.precio }}
                                        </strike>
                                        &nbsp;
                                        ${{ producto.oferta_precio }}
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'producto_id' producto.id %}">Ver producto</a></div>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div class="col mb-5">
                            <div class="card h-100">
                                <!-- Product image-->
                                <img class="card-img-top" src="{{ producto.imagen.url }}" alt="..." />
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{ producto.nombre }}</h5>
                                        <!-- Product price-->
                                        ${{ producto.precio }}
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'producto_id' producto.id %}">Ver producto</a></div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}

            </div>
        </div>
    </section>
{% endblock %}

tienda/templates/login.html
{% extends 'base.html' %}
{% block content %}

<!-- Header -->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Inicia sesión</h1>
            <p class="lead fw-normal text-white-50 mb-0">para comprar en Mechá!</p>
        </div>
    </div>
</header>

<!-- Acerca de -->
<div class="container">
    <div class="row">
        <center>
            <div class="col-8">
                <br>
                <br>
                <br>
                <br>

                <form method="POST" action="{% url 'login' %}">
                    {% csrf_token %}
                    <!-- Input -->
                    <div class="mb-3">
                      <input type="text" class="form-control" name="username" placeholder="Ingresa tu usuario">
                    </div>
                    <div class="mb-3">
                      <input type="password" class="form-control" name="password" placeholder="Ingresa tu contraseña">
                    </div>

                    <!-- Boton inicio -->
                    <button type="submit" class="btn btn-secondary">Iniciar sesión</button>
                </form>

                <br>
                <br>
                <br>
                <br>
            </div>
        </center>
    </div>
</div>

{% endblock %}

tienda/templates/nosotros.html
{% extends 'base.html' %}
{% block content %}

<!-- Header -->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Mechá</h1>
            <p class="lead fw-normal text-white-50 mb-0">Somos un taller mecánico!</p>
        </div>
    </div>
</header>

<!-- Acerca de -->
<div class="container">
    <div class="row">
        <center>
            <div class="col-8">
                <p align="justify">
                    <br>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean a quam venenatis, dictum nisl eget, convallis ex. 
                    Vestibulum tempor ligula ut hendrerit bibendum. Duis ac dictum lacus. Duis cursus neque arcu, eget ultrices quam porttitor sit amet. 
                    Quisque accumsan id massa in malesuada. Vestibulum vestibulum sem nec enim pharetra varius. In nec lectus ligula. Sed in est rutrum, hendrerit justo ut, luctus erat. 
                    Nulla porttitor vulputate ullamcorper. Cras ac turpis et tellus tristique volutpat. Morbi nec ultrices nunc.
                    <br>
                    Nunc at fermentum lorem. Donec a ultrices quam. Praesent mollis, purus nec sodales posuere, tortor nulla eleifend nibh, et molestie elit lectus vitae nibh. 
                    Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas a sodales odio. Proin egestas ipsum a iaculis tincidunt. 
                    Curabitur laoreet quam et ligula efficitur, sed vulputate justo vulputate. Aliquam accumsan urna id nibh mollis eleifend.
                    <br>
                    Phasellus eleifend, nisl vel suscipit sodales, urna ante egestas dolor, a tristique tellus lectus et nibh. Sed non sollicitudin nibh, a aliquam quam. 
                    Morbi dapibus sit amet ipsum quis sodales. Pellentesque imperdiet suscipit consequat. In eget mollis nunc. Etiam pellentesque scelerisque justo eu molestie. 
                    Proin facilisis sagittis massa, rhoncus lobortis libero tristique sed. Aliquam non velit sit amet ex dapibus rutrum. 
                    <br>
                </p>
            </div>
        </center>
    </div>
</div>

{% endblock %}

tienda/templates/register.html
{% extends 'base.html' %}
{% block content %}

<!-- Header -->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Registrate</h1>
            <p class="lead fw-normal text-white-50 mb-0">para ser parte de Mechá!</p>
        </div>
    </div>
</header>

<!-- Acerca de -->
<div class="container">
    <div class="row">
        <center>
            <div class="col-8">
                <br>
                <br>
                <br>
                <br>

                <form method="POST" action="{% url 'register' %}">
                    {% csrf_token %}
                    <!-- Input -->
                    {{ form.as_p }}
                    <br>
                    <button type="submit" class="btn btn-secondary"> Registrarse </button>
                  </form>

                <br>
                <br>
                <br>
                <br>
            </div>
        </center>
    </div>
</div>

{% endblock %}